# -*- coding: utf-8 -*-
"""Efficient Two-Stock Portfolio Optimiser 4 Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x5jfh_4GUSpZZcJdwjd9fed5nf0zHwg_
"""

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

st.set_page_config(page_title="Efficient Portfolio Calculator", layout="centered")

st.title("Efficient Portfolio Calculator")
st.markdown("Built using Modern Portfolio Theory. Enter an index or a list of tickers to find the optimal two-stock portfolio.")

# Input section
input_type = st.radio("Select input type", ["Index", "Custom tickers"])

index_map = {
    'NASDAQ100': ('https://en.wikipedia.org/wiki/Nasdaq-100', 5, 'Ticker'),
    'SP500': ('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies', 0, 'Symbol'),
    'FTSE100': ('https://en.wikipedia.org/wiki/FTSE_100', 4, 'Ticker')
}

if input_type == "Index":
    selected_index = st.selectbox("Select index", list(index_map.keys()))
else:
    custom_input = st.text_input("Enter tickers separated by commas (e.g. AAPL, NVDA, AMD, MSFT)")

start_date = st.date_input("Start date", value=pd.to_datetime("2023-01-01"))
end_date = st.date_input("End date", value=pd.to_datetime("today"))

run = st.button("Run optimiser")

if run:
    with st.spinner("Fetching data and running optimisation..."):

        # Get tickers
        if input_type == "Index":
            url, table_index, ticker_col = index_map[selected_index]
            tables = pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0"})
            tickers = tables[table_index][ticker_col].tolist()
        else:
            tickers = [t.strip() for t in custom_input.split(",")]

        # Download price data
        data = yf.download(tickers, start=str(start_date), end=str(end_date), progress=False)
        close_prices = data['Close'].dropna(axis=1)
        returns = close_prices.pct_change().dropna()

        # Correlation matrix
        correlation_matrix = correlation_matrix.where(
        ~np.eye(len(correlation_matrix), dtype=bool)
        )

        # Find lowest correlation pair
        min_corr = correlation_matrix.stack().idxmin()
        stock1, stock2 = min_corr[0], min_corr[1]

        st.subheader(f"Lowest correlation pair: {stock1} and {stock2}")
        st.write(f"Correlation: {correlation_matrix.loc[stock1, stock2]:.4f}")

        # Download pair data
        pair = yf.download([stock1, stock2], start=str(start_date), end=str(end_date), progress=False)
        pair_returns = pair['Close'].pct_change().dropna()

        # Stats
        stock1_ret = float(pair_returns[stock1].mean())
        stock2_ret = float(pair_returns[stock2].mean())
        stock1_var = float(pair_returns[stock1].var())
        stock2_var = float(pair_returns[stock2].var())
        correlation = float(correlation_matrix.loc[stock1, stock2])

        # Risk free rate
        risk_free = yf.download('^TNX', progress=False)
        risk_free_rate = risk_free['Close'].iloc[-1].item() / 100

        # Optimisation loop
        returns_list = []
        volatility_list = []
        best_sharpe = -np.inf
        best_weight = 0

        for w in np.arange(0, 1.01, 0.01):
            port_return = float((w * stock1_ret + (1 - w) * stock2_ret) * 252)
            port_variance = float(((w**2) * stock1_var + ((1-w)**2) * stock2_var + 2*w*(1-w)*np.sqrt(stock1_var)*np.sqrt(stock2_var)*correlation) * 252)
            port_vol = np.sqrt(port_variance)
            returns_list.append(port_return)
            volatility_list.append(port_vol)
            sharpe = (port_return - risk_free_rate) / port_vol

            if sharpe > best_sharpe:
                best_sharpe = sharpe
                best_weight = w

        # Results
        st.subheader("Optimal portfolio")
        col1, col2, col3 = st.columns(3)
        col1.metric(f"{stock1} weight", f"{best_weight:.0%}")
        col2.metric(f"{stock2} weight", f"{1 - best_weight:.0%}")
        col3.metric("Sharpe ratio", f"{best_sharpe:.4f}")

        # Efficient frontier plot
        opt_vol = np.sqrt(
            (best_weight**2)*stock1_var*252 +
            ((1-best_weight)**2)*stock2_var*252 +
            2*best_weight*(1-best_weight)*np.sqrt(stock1_var)*np.sqrt(stock2_var)*correlation*252
        )
        opt_ret = best_weight * stock1_ret * 252 + (1 - best_weight) * stock2_ret * 252

        fig, ax = plt.subplots(figsize=(10, 6))
        ax.scatter(volatility_list, returns_list, c='blue', s=10, label='Portfolio combinations')
        ax.scatter(opt_vol, opt_ret, c='red', marker='x', s=200, label='Optimal portfolio')
        ax.set_xlabel('Annual volatility')
        ax.set_ylabel('Annual return')
        ax.set_title(f'Efficient frontier: {stock1} vs {stock2}')
        ax.legend()
        st.pyplot(fig)

        st.caption(f"Risk-free rate (10Y Treasury): {risk_free_rate:.2%}")
