# -*- coding: utf-8 -*-
"""Efficient Two-Stock Portfolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBaMEynqx-VVhJOvu1ORSftIvGirQ8nn
"""

#Importing relevant libraries
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

#Reading the website to find the tickers
tables = pd.read_html('https://en.wikipedia.org/wiki/Nasdaq-100',
                      storage_options={"User-Agent": "Mozilla/5.0"})

for i, table in enumerate(tables):
    print(i, table.columns.tolist())

#Finding the tickers in the index
tickers = tables[5]['Ticker'].tolist()
print(tickers)

data = yf.download(tickers)

#Finding the closing price data for the companies
close_prices = data['Close']
returns = close_prices.pct_change().dropna()

returns.head()

#Creating the correlation matrix for all the stocks
correlation_matrix = returns.corr()
print(correlation_matrix)

#Removing self-correlations by setting diagonal to NaN
np.fill_diagonal(correlation_matrix.values, np.nan)

#Finding the pair with lowest correlation
min_corr = correlation_matrix.stack().idxmin()
print(min_corr)

#Fetching the data for the two stocks
pair = yf.download(min_corr)
pair.head()

#Getting the closing price data for the stocks
close_pair = pair['Close']
pair_returns = close_pair.pct_change().dropna()
print(pair_returns)

#Fetching the risk free rate as the 10 year Treasury yield
risk_free = yf.download('^TNX')
risk_free.head()
risk_free.iloc[-1]

risk_free_rate = risk_free['Close'].iloc[-1] / 100
print(risk_free_rate)

daily_rf = float(risk_free_rate / 252)
print(daily_rf)

#Finding the average returns, variance and correlation for both the stocks
avgo_ret = float(pair_returns['AVGO'].mean())
orly_ret = float(pair_returns['ORLY'].mean())
print(avgo_ret)
print(orly_ret)
avgo_var = float(pair_returns['AVGO'].var())
orly_var = float(pair_returns['ORLY'].var())
print(avgo_var)
print(orly_var)
correlation = float(correlation_matrix.loc['AVGO', 'ORLY'])
print(correlation)

print(type(risk_free_rate))
print(risk_free_rate)

returns_list = []
volatility_list = []

best_sharpe = -np.inf
best_weight = 0

#Finding the optimal weighting of the two stocks
for w in np.arange(0, 1.01, 0.01):
    port_return = w*avgo_ret + (1-w)*orly_ret
    port_variance = (w**2)*avgo_var + ((1-w)**2)*orly_var + 2*w*(1-w)*np.sqrt(avgo_var)*np.sqrt(orly_var)*correlation
    port_return = float(port_return * 252)
    port_variance = float(port_variance * 252)
    port_vol = np.sqrt(port_variance)
    returns_list.append(port_return)
    volatility_list.append(port_vol)
    sharpe = (port_return - risk_free_rate) / port_vol

    if sharpe > best_sharpe:
        best_sharpe = sharpe
        best_weight = w

print(f"Optimal weight in AVGO: {best_weight:.2f}")
print(f"Optimal weight in ORLY: {1 - best_weight:.2f}")
print(f"Sharpe ratio: {best_sharpe:.4f}")

#Plotting the efficient frontier
plt.figure(figsize=(10, 6))
plt.scatter(volatility_list, returns_list, c='blue', marker='o', s=10)
plt.scatter(np.sqrt((best_weight**2)*avgo_var*252 + ((1-best_weight)**2)*orly_var*252 + 2*best_weight*(1-best_weight)*np.sqrt(avgo_var)*np.sqrt(orly_var)*correlation*252),
            best_weight*avgo_ret*252 + (1-best_weight)*orly_ret*252,
            c='red', marker='x', s=200, label='Optimal portfolio')
plt.xlabel('Annual volatility')
plt.ylabel('Annual return')
plt.title('Efficient frontier: AVGO vs ORLY')
plt.legend()
plt.show()